// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjdiVmfx10LyceW2KOBQCCQAfW_3HmwcM',
    appId: '1:1019137659278:web:c0aa791e32cc7394c054df',
    messagingSenderId: '1019137659278',
    projectId: 'store-920920',
    authDomain: 'store-920920.firebaseapp.com',
    storageBucket: 'store-920920.appspot.com',
    measurementId: 'G-FCVJFMJMYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdnOm-cujwojxoVrCcmO7Hl9ALB7ncKSs',
    appId: '1:1019137659278:android:fba40668f70609c0c054df',
    messagingSenderId: '1019137659278',
    projectId: 'store-920920',
    storageBucket: 'store-920920.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvQ_wtQIhUOKQpLEKT9sFFKvJC6qdMDio',
    appId: '1:1019137659278:ios:64f494715a4c35b8c054df',
    messagingSenderId: '1019137659278',
    projectId: 'store-920920',
    storageBucket: 'store-920920.appspot.com',
    androidClientId: '1019137659278-749ujd3rrfvonfmlsqvk1nnc02b07ndk.apps.googleusercontent.com',
    iosClientId: '1019137659278-bk3fhdm3r0rv8uoh4jkqvfuchfasate7.apps.googleusercontent.com',
    iosBundleId: 'com.dontshop.now.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvQ_wtQIhUOKQpLEKT9sFFKvJC6qdMDio',
    appId: '1:1019137659278:ios:64f494715a4c35b8c054df',
    messagingSenderId: '1019137659278',
    projectId: 'store-920920',
    storageBucket: 'store-920920.appspot.com',
    androidClientId: '1019137659278-749ujd3rrfvonfmlsqvk1nnc02b07ndk.apps.googleusercontent.com',
    iosClientId: '1019137659278-bk3fhdm3r0rv8uoh4jkqvfuchfasate7.apps.googleusercontent.com',
    iosBundleId: 'com.dontshop.now.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjdiVmfx10LyceW2KOBQCCQAfW_3HmwcM',
    appId: '1:1019137659278:web:4555f55264a28e46c054df',
    messagingSenderId: '1019137659278',
    projectId: 'store-920920',
    authDomain: 'store-920920.firebaseapp.com',
    storageBucket: 'store-920920.appspot.com',
    measurementId: 'G-Z8FJ04BGQ0',
  );
}
